// Generated by CoffeeScript 1.12.7
(function() {
  var arr, arr1, arr2, el, i, j, k, l, len, len1, len2, len3, len4, len5, m, n, o, p, r1, r2, v, worker, workers;

  arr1 = ["foo", "bar", "bim"];

  for (i = 0, len = arr1.length; i < len; i++) {
    el = arr1[i];
    console.log("el = ", el);
  }

  console.log();

  for (j = 0, len1 = arr1.length; j < len1; j++) {
    el = arr1[j];
    console.log(el);
  }

  console.log();

  worker = {
    fname: "foo",
    lname: "bar",
    age: 10
  };

  console.log(worker);

  for (k in worker) {
    v = worker[k];
    console.log(k, "=> ", v);
  }

  console.log();

  workers = [
    {
      fname: "foo",
      lname: "bar",
      age: 10
    }, {
      fname: "edu",
      lname: "tilos",
      age: 20
    }, {
      fname: "leo",
      lname: "messi",
      age: 30
    }
  ];

  for (l = 0, len2 = workers.length; l < len2; l++) {
    worker = workers[l];
    for (k in worker) {
      v = worker[k];
      console.log(k, "=> ", v);
    }
    console.log();
  }

  console.log();

  workers = [
    {
      fname: "new_foo",
      lname: "new_bar",
      age: 10
    }, {
      fname: "new_edu",
      lname: "new_tilos",
      age: 20
    }, {
      fname: "new_leo",
      lname: "new_messi",
      age: 30
    }
  ];

  for (m = 0, len3 = workers.length; m < len3; m++) {
    worker = workers[m];
    for (k in worker) {
      v = worker[k];
      console.log(k, "=> ", v);
    }
    console.log();
  }

  console.log();

  r1 = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10];

  console.log("r1 = ", r1);

  r2 = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9];

  console.log("r2 = ", r2);

  arr = [1, 2, 3, 4, 5, 6, 7, 8];

  console.log(arr.slice(0, 4));

  console.log(arr.slice(0, 3));

  console.log(arr.slice(-3));

  console.log(arr.slice(-3));

  for (o = 0, len4 = r1.length; o < len4; o++) {
    n = r1[o];
    console.log(n);
  }

  console.log();

  for (p = 0, len5 = r1.length; p < len5; p++) {
    n = r1[p];
    console.log(n);
  }

  arr2 = (function() {
    var len6, q, results;
    results = [];
    for (q = 0, len6 = r1.length; q < len6; q += 3) {
      n = r1[q];
      results.push(n);
    }
    return results;
  })();

  console.log(arr2);

}).call(this);

//# sourceMappingURL=ArrayAndObjectExample.js.map
