// Generated by CoffeeScript 1.12.7
(function() {
  var age, name, res, weekday;

  age = 10;

  if (age > 0 && age < 10) {
    console.log("you are child.");
  } else if (age >= 10 && age < 20) {
    console.log("you are teen.");
  } else if (age >= 20 && age < 35) {
    console.log("you are young.");
  } else {
    console.log("you are old.");
  }

  if (age === 10) {
    console.log("you are 10.");
  } else {
    console.log("you are not 10.");
  }

  weekday = "Tuesday";

  res = (function() {
    switch (false) {
      case weekday !== "Monday":
        return "It's Monday.";
      case weekday !== "Tuesday":
        return "It's Tuesday.";
      case weekday !== "Wednesday":
        return "It's Wednesday.";
      case weekday !== "Thursday":
        return "It's Thursday.";
      case weekday !== "Friday":
        return "It's Friday.";
      case weekday !== "Saturday":
        return "It's Saturday.";
      default:
        return "It's Sunday or unknown weekday.";
    }
  })();

  console.log("res = ", res);

  name = "foo";

  res = (function() {
    switch (name) {
      case "foo":
      case "bar":
        return "you are foo or bar.";
      case "edu":
      case "tilos":
        return "you are edu or tilos.";
      case "leo":
      case "messi":
        return "you are leo or messi.";
    }
  })();

  console.log("res = ", res);

  if (name === "foo") {
    res = true;
  }

  console.log("res = ", res);

  if (name === "foo") {
    res = true;
  }

  console.log("res = ", res);

}).call(this);

//# sourceMappingURL=Conditionals.js.map
