// Generated by CoffeeScript 1.12.7
(function() {
  var add, add2, age, divide, multiply, n1, n2, name, res, subtract;

  name = "foo";

  age = 10;

  console.log("name = " + name + " and age = " + age);


  /*
    multi
    line
    comment
   */

  add = function(n1, n2) {
    var res;
    res = n1 + n2;
    return res;
  };

  subtract = function(n1, n2) {
    var res;
    res = n1 - n2;
    return res;
  };

  multiply = function(n1, n2) {
    var res;
    res = n1 * n2;
    return res;
  };

  divide = function(n1, n2) {
    var res;
    res = n1 / n2;
    return res;
  };

  n1 = 20;

  n2 = 10;

  console.log("add = ", add(n1, n2));

  console.log("subtract = ", subtract(n1, n2));

  console.log("multiply = ", multiply(n1, n2));

  console.log("divide = ", divide(n1, n2));

  res = add(10, 20);

  console.log("res = ", res);

  add2 = function(n1, n2) {
    if (n1 == null) {
      n1 = 10;
    }
    if (n2 == null) {
      n2 = 20;
    }
    res = n1 + n2;
    return res;
  };

  console.log("add2 = ", add2(n1, n2));

}).call(this);

//# sourceMappingURL=Example1.js.map
