// Generated by CoffeeScript 1.12.7
(function() {
  var add, divide, multiply, print_props, subtract, testFunctions,
    slice = [].slice;

  add = function(n1, n2) {
    return n1 + n2;
  };

  subtract = function(n1, n2) {
    return n1 - n2;
  };

  multiply = function(n1, n2) {
    return n1 * n2;
  };

  divide = function(n1, n2) {
    return n1 / n2;
  };

  testFunctions = function() {
    var n1, n2, res;
    n1 = 20;
    n2 = 10;
    console.log("add = ", add(n1, n2));
    console.log("subtract = ", subtract(n1, n2));
    console.log("multiply = ", multiply(n1, n2));
    console.log("divide = ", divide(n1, n2));
    res = add(n1, n2);
    return console.log("res = ", res);
  };

  testFunctions();

  print_props = function() {
    var first, i, j, last, len, other, others, second;
    first = arguments[0], second = arguments[1], others = 4 <= arguments.length ? slice.call(arguments, 2, i = arguments.length - 1) : (i = 2, []), last = arguments[i++];
    console.log("first = ", first);
    console.log("last = ", last);
    for (j = 0, len = others.length; j < len; j++) {
      other = others[j];
      console.log("member = ", other);
    }
    return console.log("last = ", last);
  };

  print_props("foo", "bar", "bim", "pako", "edu", "tilos", "leo", "messi");

}).call(this);

//# sourceMappingURL=FunctionExample.js.map
