// Generated by CoffeeScript 1.12.7
(function() {
  var n;

  n = 10;

  while (n > 0) {
    console.log("n = ", n);
    n--;
  }

  console.log();

  while (!(n > 10)) {
    console.log("n = ", n);
    n++;
  }

  n = 0;

  console.log();

  while (true) {
    console.log("n = ", n);
    n++;
    if (n === 5) {
      break;
    }
  }

  console.log();

}).call(this);

//# sourceMappingURL=Loops.js.map
