// Generated by CoffeeScript 1.12.7

/*
E
LN2
LN10
LOG2E
LOG10E
PI
SQRT1_2
SQRT2
 */

(function() {
  var n;

  console.log("E = ", Math.E);

  console.log("LN2 = ", Math.LN2);

  console.log("LN10 = ", Math.LN10);

  console.log("LOG2E = ", Math.LOG2E);

  console.log("LOG10E = ", Math.LOG10E);

  console.log("PI = ", Math.PI);

  console.log("SQRT1_2 = ", Math.SQRT1_2);

  console.log("SQRT2 = ", Math.SQRT2);

  console.log();

  n = 10.1234;

  console.log("ceil = ", Math.ceil(n));

  console.log("floor = ", Math.floor(n));

  console.log("round = ", Math.round(n));

  console.log("min = ", Math.min(1, 2, 3, 4));

  console.log("max = ", Math.max(1, 2, 3, 4));

  console.log("random = ", Math.random());

  console.log("sin(PI/6) = ", Math.sin(Math.PI / 6));

  console.log("cos(PI/6) = ", Math.cos(Math.PI / 6));

  console.log("tan(PI/6) = ", Math.tan(Math.PI / 6));

  console.log("PI/6 = ", Math.PI / 6);

  console.log("asin(sin(PI/6)) = ", Math.asin(Math.sin(Math.PI / 6)));

  console.log("acos(cos(PI/6)) = ", Math.acos(Math.cos(Math.PI / 6)));

  console.log("atan(tan(PI/6)) = ", Math.atan(Math.tan(Math.PI / 6)));

}).call(this);

//# sourceMappingURL=MathExample.js.map
